services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning

  ecoflow_metrics_exporter:
    image: afrunt/ecoflow-metrics-exporter:latest
    container_name: ecoflow-metrics-exporter
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.yaml:/application.yaml