{
 "title": "Ecoflow Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ecoflowDevice", "label": "Ecoflow Device", "query": { "query": "label_values(device) " } }
  ]
 },
 "panels": [
  {
   "title": "Remaining Time, Hours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_remainTime{device=\"$ecoflowDevice\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input, Watts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_wattsInSum{device=\"$ecoflowDevice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output, Watts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_wattsOutSum{device=\"$ecoflowDevice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ecoflow_wattsInSum{device=\"$ecoflowDevice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ecoflow_wattsOutSum{device=\"$ecoflowDevice\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}